spring:
  application:
    name: springboot-docker-postgresql
    
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/DockerDemo
    username: postgres
    password: postgres
    
  jpa:
    hibernate:
      ddl-auto: update
