FROM openjdk:17-oracle
COPY target/springboot-docker-postgresql-0.0.1-SNAPSHOT.jar springboot-docker-postgresql-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "springboot-docker-postgresql-0.0.1-SNAPSHOT.jar"]