services:

  java_app:
    container_name: springboot-docker-postgresql
    image: pavansatish1/springboot-docker-postgresql:0.0.1
    build: .
    ports:
    - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/DockerDemo
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:latest
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      
    
volumes:
  pgdata: {}